#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-getrawdata/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-getrawdata/tmp.6894aac5" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-getrawdata/tmp.6894aac5")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-getrawdata/execution

)
outfeff3b4d="${tmpDir}/out.$$" errfeff3b4d="${tmpDir}/err.$$"
mkfifo "$outfeff3b4d" "$errfeff3b4d"
trap 'rm "$outfeff3b4d" "$errfeff3b4d"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-getrawdata/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-getrawdata/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-getrawdata/execution/stdout' < "$outfeff3b4d" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-getrawdata/execution/stderr' < "$errfeff3b4d" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-getrawdata/execution


ls /home/user08/rna-seq/rawdata/*fastq.gz > rawdatapath.txt
)  > "$outfeff3b4d" 2> "$errfeff3b4d"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-getrawdata/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-getrawdata/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-getrawdata/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-getrawdata/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-getrawdata/execution/rc
