#!/bin/bash

cd /cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/tmp.76d34e0e" && echo "/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/tmp.76d34e0e")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/execution

)
outcfd0ebae="${tmpDir}/out.$$" errcfd0ebae="${tmpDir}/err.$$"
mkfifo "$outcfd0ebae" "$errcfd0ebae"
trap 'rm "$outcfd0ebae" "$errcfd0ebae"' EXIT
touch '/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/execution/stdout' '/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/execution/stderr'
tee '/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/execution/stdout' < "$outcfd0ebae" &
tee '/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/execution/stderr' < "$errcfd0ebae" >&2 &
(
cd /cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/execution


fastqc /cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/inputs/1972885663/S1.R2.fastq.gz -o .
)  > "$outcfd0ebae" 2> "$errcfd0ebae"
echo $? > /cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/execution
sync


)
mv /cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/execution/rc.tmp /cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-fastqc/shard-1/execution/rc
