#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-getPaired/shard-1/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-getPaired/shard-1/tmp.b9cb6fc9" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-getPaired/shard-1/tmp.b9cb6fc9")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-getPaired/shard-1/execution

)
out6fc02987="${tmpDir}/out.$$" err6fc02987="${tmpDir}/err.$$"
mkfifo "$out6fc02987" "$err6fc02987"
trap 'rm "$out6fc02987" "$err6fc02987"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-getPaired/shard-1/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-getPaired/shard-1/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-getPaired/shard-1/execution/stdout' < "$out6fc02987" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-getPaired/shard-1/execution/stderr' < "$err6fc02987" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-getPaired/shard-1/execution


ls /home/user08/rna-seq/rawdata/S1.R2.fastq.gz| awk -F'.' '{print $1}' > result | ls $PWD/$result*.fastq.gz  > path && \
v1=`head -n1 path` | echo $v1 > S1.R2R1.txt && \
v1=`tail -n1 path` | echo $v1 > S1.R2R2.txt
)  > "$out6fc02987" 2> "$err6fc02987"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-getPaired/shard-1/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-getPaired/shard-1/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-getPaired/shard-1/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-getPaired/shard-1/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-getPaired/shard-1/execution/rc
