#!/bin/bash

cd /cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/tmp.ac46040f" && echo "/cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/tmp.ac46040f")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/execution

)
out545ab7c2="${tmpDir}/out.$$" err545ab7c2="${tmpDir}/err.$$"
mkfifo "$out545ab7c2" "$err545ab7c2"
trap 'rm "$out545ab7c2" "$err545ab7c2"' EXIT
touch '/cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/execution/stdout' '/cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/execution/stderr'
tee '/cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/execution/stdout' < "$out545ab7c2" &
tee '/cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/execution/stderr' < "$err545ab7c2" >&2 &
(
cd /cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/execution


fastqc /cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/inputs/1972885663/S1.R1.fastq.gz -o .
)  > "$out545ab7c2" 2> "$err545ab7c2"
echo $? > /cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/execution
sync


)
mv /cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/execution/rc.tmp /cromwell-executions/rnaseq/545ab7c2-e43c-4554-8133-196511b03922/call-fastqc/shard-0/execution/rc
