#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getPaired/shard-0/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getPaired/shard-0/tmp.6a7c3cc4" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getPaired/shard-0/tmp.6a7c3cc4")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getPaired/shard-0/execution

)
outc3e14391="${tmpDir}/out.$$" errc3e14391="${tmpDir}/err.$$"
mkfifo "$outc3e14391" "$errc3e14391"
trap 'rm "$outc3e14391" "$errc3e14391"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getPaired/shard-0/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getPaired/shard-0/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getPaired/shard-0/execution/stdout' < "$outc3e14391" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getPaired/shard-0/execution/stderr' < "$errc3e14391" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getPaired/shard-0/execution


cd /home/user08/rna-seq/rawdata && \
ls S1.R1.fastq.gz| awk -F'.' '{print $1}' > result | ls $PWD/$result*.fastq.gz  > path && \
v1=`head -n1 path` | echo $v1 > S1.R1.txt && \
v2=`tail -n1 path` | echo $v2 > S1.R1.txt
)  > "$outc3e14391" 2> "$errc3e14391"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getPaired/shard-0/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getPaired/shard-0/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getPaired/shard-0/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getPaired/shard-0/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getPaired/shard-0/execution/rc
