#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-getrawdata/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-getrawdata/tmp.12d1b2c3" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-getrawdata/tmp.12d1b2c3")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-getrawdata/execution

)
outc1092b8e="${tmpDir}/out.$$" errc1092b8e="${tmpDir}/err.$$"
mkfifo "$outc1092b8e" "$errc1092b8e"
trap 'rm "$outc1092b8e" "$errc1092b8e"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-getrawdata/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-getrawdata/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-getrawdata/execution/stdout' < "$outc1092b8e" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-getrawdata/execution/stderr' < "$errc1092b8e" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-getrawdata/execution


ls /home/user08/rna-seq/rawdata/*fastq.gz > rawdatapath.txt

#rawdata=`ls /home/user08/rna-seq/rawdata/*.fq`
#for eachfile in $rawdata
#do
#   echo $eachfile > rawdatapath.txt
#done
)  > "$outc1092b8e" 2> "$errc1092b8e"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-getrawdata/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-getrawdata/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-getrawdata/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-getrawdata/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-getrawdata/execution/rc
