#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getPaired/shard-1/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getPaired/shard-1/tmp.d482b53a" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getPaired/shard-1/tmp.d482b53a")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getPaired/shard-1/execution

)
outcfd0ebae="${tmpDir}/out.$$" errcfd0ebae="${tmpDir}/err.$$"
mkfifo "$outcfd0ebae" "$errcfd0ebae"
trap 'rm "$outcfd0ebae" "$errcfd0ebae"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getPaired/shard-1/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getPaired/shard-1/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getPaired/shard-1/execution/stdout' < "$outcfd0ebae" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getPaired/shard-1/execution/stderr' < "$errcfd0ebae" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getPaired/shard-1/execution


ls /home/user08/rna-seq/rawdata/S1.R2.fastq.gz| awk -F'.' '{print $1}' > result | ls $PWD/$result*.fastq.gz  > path && \
v1=`head -n1 path` | echo $v1 > S1.R2R1.txt && \
v1=`tail -n1 path` | echo $v1 > S1.R2R2.txt
)  > "$outcfd0ebae" 2> "$errcfd0ebae"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getPaired/shard-1/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getPaired/shard-1/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getPaired/shard-1/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getPaired/shard-1/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getPaired/shard-1/execution/rc
