#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getrawdata/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getrawdata/tmp.2a87ae39" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getrawdata/tmp.2a87ae39")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getrawdata/execution

)
outc3e14391="${tmpDir}/out.$$" errc3e14391="${tmpDir}/err.$$"
mkfifo "$outc3e14391" "$errc3e14391"
trap 'rm "$outc3e14391" "$errc3e14391"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getrawdata/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getrawdata/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getrawdata/execution/stdout' < "$outc3e14391" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getrawdata/execution/stderr' < "$errc3e14391" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getrawdata/execution


ls /home/user08/rna-seq/rawdata/*fastq.gz > rawdatapath.txt
)  > "$outc3e14391" 2> "$errc3e14391"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getrawdata/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getrawdata/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getrawdata/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getrawdata/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-getrawdata/execution/rc
