#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-getrawdata/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-getrawdata/tmp.3ab3094d" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-getrawdata/tmp.3ab3094d")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-getrawdata/execution

)
outf1d89814="${tmpDir}/out.$$" errf1d89814="${tmpDir}/err.$$"
mkfifo "$outf1d89814" "$errf1d89814"
trap 'rm "$outf1d89814" "$errf1d89814"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-getrawdata/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-getrawdata/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-getrawdata/execution/stdout' < "$outf1d89814" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-getrawdata/execution/stderr' < "$errf1d89814" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-getrawdata/execution


ls /home/user08/rna-seq/rawdata/*fastq.gz > rawdatapath.txt
)  > "$outf1d89814" 2> "$errf1d89814"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-getrawdata/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-getrawdata/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-getrawdata/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-getrawdata/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-getrawdata/execution/rc
