#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-getrawdata/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-getrawdata/tmp.0478b778" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-getrawdata/tmp.0478b778")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-getrawdata/execution

)
out38edd286="${tmpDir}/out.$$" err38edd286="${tmpDir}/err.$$"
mkfifo "$out38edd286" "$err38edd286"
trap 'rm "$out38edd286" "$err38edd286"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-getrawdata/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-getrawdata/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-getrawdata/execution/stdout' < "$out38edd286" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-getrawdata/execution/stderr' < "$err38edd286" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-getrawdata/execution


ls /home/user08/rna-seq/rawdata/*fastq.gz > rawdatapath.txt
)  > "$out38edd286" 2> "$err38edd286"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-getrawdata/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-getrawdata/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-getrawdata/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-getrawdata/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-getrawdata/execution/rc
