#!/bin/bash

cd /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/tmp.23122e14" && echo "/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/tmp.23122e14")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/execution

)
outfeff3b4d="${tmpDir}/out.$$" errfeff3b4d="${tmpDir}/err.$$"
mkfifo "$outfeff3b4d" "$errfeff3b4d"
trap 'rm "$outfeff3b4d" "$errfeff3b4d"' EXIT
touch '/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/execution/stdout' '/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/execution/stderr'
tee '/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/execution/stdout' < "$outfeff3b4d" &
tee '/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/execution/stderr' < "$errfeff3b4d" >&2 &
(
cd /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/execution


fastqc /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/inputs/1972885663/S1.R1.fastq.gz /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/inputs/1972885663/S1.R2.fastq.gz -o .
)  > "$outfeff3b4d" 2> "$errfeff3b4d"
echo $? > /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/execution
sync


)
mv /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/execution/rc.tmp /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-fastqc/execution/rc
