#!/bin/bash

cd /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/tmp.10d05342" && echo "/cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/tmp.10d05342")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/execution

)
outa64a0288="${tmpDir}/out.$$" erra64a0288="${tmpDir}/err.$$"
mkfifo "$outa64a0288" "$erra64a0288"
trap 'rm "$outa64a0288" "$erra64a0288"' EXIT
touch '/cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/execution/stdout' '/cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/execution/stderr'
tee '/cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/execution/stdout' < "$outa64a0288" &
tee '/cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/execution/stderr' < "$erra64a0288" >&2 &
(
cd /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/execution


java -jar /opt/Trimmomatic-0.39/trimmomatic-0.39.jar SE -phred33 \
 /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/inputs/1972885663/S1.fastq.gz S1.out.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
)  > "$outa64a0288" 2> "$erra64a0288"
echo $? > /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/execution
sync


)
mv /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/execution/rc.tmp /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-trim/shard-0/execution/rc
