#!/bin/bash

cd /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/tmp.c2962310" && echo "/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/tmp.c2962310")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/execution

)
out38edd286="${tmpDir}/out.$$" err38edd286="${tmpDir}/err.$$"
mkfifo "$out38edd286" "$err38edd286"
trap 'rm "$out38edd286" "$err38edd286"' EXIT
touch '/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/execution/stdout' '/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/execution/stderr'
tee '/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/execution/stdout' < "$out38edd286" &
tee '/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/execution/stderr' < "$err38edd286" >&2 &
(
cd /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/execution


java -jar /opt/Trimmomatic-0.39/trimmomatic-0.39.jar SE -phred33 \
 /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/inputs/1972885663/S1.fastq.gz S1.out.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
)  > "$out38edd286" 2> "$err38edd286"
echo $? > /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/execution
sync


)
mv /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/execution/rc.tmp /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-trim/shard-0/execution/rc
