#!/bin/bash

cd /cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/tmp.e6293d98" && echo "/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/tmp.e6293d98")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/execution

)
outa7f1659e="${tmpDir}/out.$$" erra7f1659e="${tmpDir}/err.$$"
mkfifo "$outa7f1659e" "$erra7f1659e"
trap 'rm "$outa7f1659e" "$erra7f1659e"' EXIT
touch '/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/execution/stdout' '/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/execution/stderr'
tee '/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/execution/stdout' < "$outa7f1659e" &
tee '/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/execution/stderr' < "$erra7f1659e" >&2 &
(
cd /cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/execution


fastqc /cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/inputs/1972885663/S1.R1.fastq.gz /cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/inputs/1972885663/S1.R2.fastq.gz -o .
)  > "$outa7f1659e" 2> "$erra7f1659e"
echo $? > /cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/execution
sync


)
mv /cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/execution/rc.tmp /cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-fastqc/execution/rc
