#!/bin/bash

cd /cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/tmp.3270c332" && echo "/cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/tmp.3270c332")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/execution

)
outb39e6a94="${tmpDir}/out.$$" errb39e6a94="${tmpDir}/err.$$"
mkfifo "$outb39e6a94" "$errb39e6a94"
trap 'rm "$outb39e6a94" "$errb39e6a94"' EXIT
touch '/cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/execution/stdout' '/cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/execution/stderr'
tee '/cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/execution/stdout' < "$outb39e6a94" &
tee '/cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/execution/stderr' < "$errb39e6a94" >&2 &
(
cd /cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/execution


java -jar /opt/Trimmomatic-0.39/trimmomatic-0.39.jar PE \
 /cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/inputs/1972885663/S1.R1.fastq.gz /cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/inputs/1972885663/S1.R2.fastq.gz \
S1.R1.out.paired.fastq.gz \
S1.R1.out.unpaired.fastq.gz \
S1.R2.out.paired.fastq.gz \
S1.R2.out.unpaired.fastq.gz \
ILLUMINACLIP:TruSeq3-PE.fa:2:30:10:2:True LEADING:3 TRAILING:3 MINLEN:36
)  > "$outb39e6a94" 2> "$errb39e6a94"
echo $? > /cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/execution
sync


)
mv /cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/execution/rc.tmp /cromwell-executions/rnaseq/b39e6a94-8d46-43e1-a7a4-3179a6e146cd/call-trim_PE/shard-1/execution/rc
