#!/bin/bash

cd /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/tmp.e1ac933f" && echo "/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/tmp.e1ac933f")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/execution

)
out38edd286="${tmpDir}/out.$$" err38edd286="${tmpDir}/err.$$"
mkfifo "$out38edd286" "$err38edd286"
trap 'rm "$out38edd286" "$err38edd286"' EXIT
touch '/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/execution/stdout' '/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/execution/stderr'
tee '/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/execution/stdout' < "$out38edd286" &
tee '/cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/execution/stderr' < "$err38edd286" >&2 &
(
cd /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/execution


fastqc /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/inputs/1972885663/S1.fastq.gz /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/inputs/1972885663/S2.fastq.gz -o .
)  > "$out38edd286" 2> "$err38edd286"
echo $? > /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/execution
sync


)
mv /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/execution/rc.tmp /cromwell-executions/rnaseq/38edd286-5b7b-496b-abee-81adc20a1f63/call-fastqc/execution/rc
