#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-getrawdata/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-getrawdata/tmp.63fa4b0f" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-getrawdata/tmp.63fa4b0f")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-getrawdata/execution

)
out940b2833="${tmpDir}/out.$$" err940b2833="${tmpDir}/err.$$"
mkfifo "$out940b2833" "$err940b2833"
trap 'rm "$out940b2833" "$err940b2833"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-getrawdata/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-getrawdata/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-getrawdata/execution/stdout' < "$out940b2833" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-getrawdata/execution/stderr' < "$err940b2833" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-getrawdata/execution


ls /home/user08/rna-seq/rawdata/*fastq.gz > rawdatapath.txt

#rawdata=`ls /home/user08/rna-seq/rawdata/*.fq`
#for eachfile in $rawdata
#do
#   echo $eachfile > rawdatapath.txt
#done
)  > "$out940b2833" 2> "$err940b2833"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-getrawdata/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-getrawdata/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-getrawdata/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-getrawdata/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-getrawdata/execution/rc
