#!/bin/bash

cd /cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/tmp.07395e25" && echo "/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/tmp.07395e25")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/execution

)
out6fc02987="${tmpDir}/out.$$" err6fc02987="${tmpDir}/err.$$"
mkfifo "$out6fc02987" "$err6fc02987"
trap 'rm "$out6fc02987" "$err6fc02987"' EXIT
touch '/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/execution/stdout' '/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/execution/stderr'
tee '/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/execution/stdout' < "$out6fc02987" &
tee '/cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/execution/stderr' < "$err6fc02987" >&2 &
(
cd /cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/execution


fastqc /cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/inputs/1972885663/S1.R1.fastq.gz -o .
)  > "$out6fc02987" 2> "$err6fc02987"
echo $? > /cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/execution
sync


)
mv /cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/execution/rc.tmp /cromwell-executions/rnaseq/6fc02987-9c8e-41dc-8204-9d8991fd4d68/call-fastqc/shard-0/execution/rc
