#!/bin/bash

cd /cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/tmp.99d54e3b" && echo "/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/tmp.99d54e3b")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/execution

)
oute347b323="${tmpDir}/out.$$" erre347b323="${tmpDir}/err.$$"
mkfifo "$oute347b323" "$erre347b323"
trap 'rm "$oute347b323" "$erre347b323"' EXIT
touch '/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/execution/stdout' '/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/execution/stderr'
tee '/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/execution/stdout' < "$oute347b323" &
tee '/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/execution/stderr' < "$erre347b323" >&2 &
(
cd /cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/execution


java -jar /opt/Trimmomatic-0.39/trimmomatic-0.39.jar SE -phred33 \
 /cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/inputs/1972885663/S1.fastq.gz output1.fq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
)  > "$oute347b323" 2> "$erre347b323"
echo $? > /cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/execution
sync


)
mv /cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/execution/rc.tmp /cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-trim/shard-0/execution/rc
