#!/bin/bash

cd /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/tmp.83458b1c" && echo "/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/tmp.83458b1c")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/execution

)
outfeff3b4d="${tmpDir}/out.$$" errfeff3b4d="${tmpDir}/err.$$"
mkfifo "$outfeff3b4d" "$errfeff3b4d"
trap 'rm "$outfeff3b4d" "$errfeff3b4d"' EXIT
touch '/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/execution/stdout' '/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/execution/stderr'
tee '/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/execution/stdout' < "$outfeff3b4d" &
tee '/cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/execution/stderr' < "$errfeff3b4d" >&2 &
(
cd /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/execution


java -jar /opt/Trimmomatic-0.39/trimmomatic-0.39.jar SE -phred33 \
 /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/inputs/1972885663/S1.R2.fastq.gz S1.R2.out.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
)  > "$outfeff3b4d" 2> "$errfeff3b4d"
echo $? > /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/execution
sync


)
mv /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/execution/rc.tmp /cromwell-executions/rnaseq/feff3b4d-e2ad-4c85-b8d6-7670905c0338/call-trim_SE/shard-1/execution/rc
