#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-getrawdata/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-getrawdata/tmp.89a88ac6" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-getrawdata/tmp.89a88ac6")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-getrawdata/execution

)
out40887bb3="${tmpDir}/out.$$" err40887bb3="${tmpDir}/err.$$"
mkfifo "$out40887bb3" "$err40887bb3"
trap 'rm "$out40887bb3" "$err40887bb3"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-getrawdata/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-getrawdata/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-getrawdata/execution/stdout' < "$out40887bb3" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-getrawdata/execution/stderr' < "$err40887bb3" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-getrawdata/execution


ls /home/user08/rna-seq/rawdata/*fastq.gz > rawdatapath.txt
)  > "$out40887bb3" 2> "$err40887bb3"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-getrawdata/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-getrawdata/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-getrawdata/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-getrawdata/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-getrawdata/execution/rc
