#!/bin/bash

cd /cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/tmp.00188a59" && echo "/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/tmp.00188a59")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/execution

)
out940b2833="${tmpDir}/out.$$" err940b2833="${tmpDir}/err.$$"
mkfifo "$out940b2833" "$err940b2833"
trap 'rm "$out940b2833" "$err940b2833"' EXIT
touch '/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/execution/stdout' '/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/execution/stderr'
tee '/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/execution/stdout' < "$out940b2833" &
tee '/cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/execution/stderr' < "$err940b2833" >&2 &
(
cd /cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/execution


fastqc /cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/inputs/1972885663/S1.fastq.gz
)  > "$out940b2833" 2> "$err940b2833"
echo $? > /cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/execution
sync


)
mv /cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/execution/rc.tmp /cromwell-executions/rnaseq/940b2833-3886-4b0a-b723-b41fe7b3f4e9/call-fastqc/execution/rc
