#!/bin/bash

cd /cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/tmp.e4878bbf" && echo "/cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/tmp.e4878bbf")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/execution

)
out90696091="${tmpDir}/out.$$" err90696091="${tmpDir}/err.$$"
mkfifo "$out90696091" "$err90696091"
trap 'rm "$out90696091" "$err90696091"' EXIT
touch '/cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/execution/stdout' '/cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/execution/stderr'
tee '/cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/execution/stdout' < "$out90696091" &
tee '/cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/execution/stderr' < "$err90696091" >&2 &
(
cd /cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/execution


fastqc /cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/inputs/1972885663/S1.R1.fastq.gz -o .
)  > "$out90696091" 2> "$err90696091"
echo $? > /cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/execution
sync


)
mv /cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/execution/rc.tmp /cromwell-executions/rnaseq/90696091-c986-4896-8f40-41ba4488e2a5/call-fastqc/shard-0/execution/rc
