#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/291d453e-27c7-4104-bd58-a0c0922a17f7/call-getrawdata/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/291d453e-27c7-4104-bd58-a0c0922a17f7/call-getrawdata/tmp.15547e85" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/291d453e-27c7-4104-bd58-a0c0922a17f7/call-getrawdata/tmp.15547e85")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/291d453e-27c7-4104-bd58-a0c0922a17f7/call-getrawdata/execution

)
out291d453e="${tmpDir}/out.$$" err291d453e="${tmpDir}/err.$$"
mkfifo "$out291d453e" "$err291d453e"
trap 'rm "$out291d453e" "$err291d453e"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/291d453e-27c7-4104-bd58-a0c0922a17f7/call-getrawdata/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/291d453e-27c7-4104-bd58-a0c0922a17f7/call-getrawdata/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/291d453e-27c7-4104-bd58-a0c0922a17f7/call-getrawdata/execution/stdout' < "$out291d453e" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/291d453e-27c7-4104-bd58-a0c0922a17f7/call-getrawdata/execution/stderr' < "$err291d453e" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/291d453e-27c7-4104-bd58-a0c0922a17f7/call-getrawdata/execution


ls /home/user08/rna-seq/rawdata/*fastq.gz > rawdatapath.txt

#rawdata=`ls /home/user08/rna-seq/rawdata/*.fq`
#for eachfile in $rawdata
#do
#   echo $eachfile > rawdatapath.txt
#done
)  > "$out291d453e" 2> "$err291d453e"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/291d453e-27c7-4104-bd58-a0c0922a17f7/call-getrawdata/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/291d453e-27c7-4104-bd58-a0c0922a17f7/call-getrawdata/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/291d453e-27c7-4104-bd58-a0c0922a17f7/call-getrawdata/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/291d453e-27c7-4104-bd58-a0c0922a17f7/call-getrawdata/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/291d453e-27c7-4104-bd58-a0c0922a17f7/call-getrawdata/execution/rc
