#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/07596b93-37ad-40cc-9404-5adf65a790f8/call-getPaired/shard-0/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/07596b93-37ad-40cc-9404-5adf65a790f8/call-getPaired/shard-0/tmp.e8d37fa5" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/07596b93-37ad-40cc-9404-5adf65a790f8/call-getPaired/shard-0/tmp.e8d37fa5")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/07596b93-37ad-40cc-9404-5adf65a790f8/call-getPaired/shard-0/execution

)
out07596b93="${tmpDir}/out.$$" err07596b93="${tmpDir}/err.$$"
mkfifo "$out07596b93" "$err07596b93"
trap 'rm "$out07596b93" "$err07596b93"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/07596b93-37ad-40cc-9404-5adf65a790f8/call-getPaired/shard-0/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/07596b93-37ad-40cc-9404-5adf65a790f8/call-getPaired/shard-0/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/07596b93-37ad-40cc-9404-5adf65a790f8/call-getPaired/shard-0/execution/stdout' < "$out07596b93" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/07596b93-37ad-40cc-9404-5adf65a790f8/call-getPaired/shard-0/execution/stderr' < "$err07596b93" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/07596b93-37ad-40cc-9404-5adf65a790f8/call-getPaired/shard-0/execution


cd /home/user08/rna-seq/rawdata
ls S1.R1.fastq.gz| awk -F'.' '{print $1}' > result | ls $PWD/$result*.fastq.gz  > path
v1=`head -n1 path` | echo $v1 > S1.R1.txt 
v2=`tail -n1 path` | echo $v2 > S1.R1.txt
)  > "$out07596b93" 2> "$err07596b93"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/07596b93-37ad-40cc-9404-5adf65a790f8/call-getPaired/shard-0/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/07596b93-37ad-40cc-9404-5adf65a790f8/call-getPaired/shard-0/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/07596b93-37ad-40cc-9404-5adf65a790f8/call-getPaired/shard-0/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/07596b93-37ad-40cc-9404-5adf65a790f8/call-getPaired/shard-0/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/07596b93-37ad-40cc-9404-5adf65a790f8/call-getPaired/shard-0/execution/rc
