#!/bin/bash

cd /cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/tmp.02e71c1c" && echo "/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/tmp.02e71c1c")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/execution

)
outc1092b8e="${tmpDir}/out.$$" errc1092b8e="${tmpDir}/err.$$"
mkfifo "$outc1092b8e" "$errc1092b8e"
trap 'rm "$outc1092b8e" "$errc1092b8e"' EXIT
touch '/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/execution/stdout' '/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/execution/stderr'
tee '/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/execution/stdout' < "$outc1092b8e" &
tee '/cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/execution/stderr' < "$errc1092b8e" >&2 &
(
cd /cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/execution


fastqc /cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/inputs/1972885663/S1.fastq.gz -o .
)  > "$outc1092b8e" 2> "$errc1092b8e"
echo $? > /cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/execution
sync


)
mv /cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/execution/rc.tmp /cromwell-executions/rnaseq/c1092b8e-8199-419d-a803-e7195c0927bb/call-fastqc/execution/rc
