#!/bin/bash

cd /cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/tmp.224df844" && echo "/cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/tmp.224df844")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/execution

)
out8ae6b526="${tmpDir}/out.$$" err8ae6b526="${tmpDir}/err.$$"
mkfifo "$out8ae6b526" "$err8ae6b526"
trap 'rm "$out8ae6b526" "$err8ae6b526"' EXIT
touch '/cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/execution/stdout' '/cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/execution/stderr'
tee '/cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/execution/stdout' < "$out8ae6b526" &
tee '/cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/execution/stderr' < "$err8ae6b526" >&2 &
(
cd /cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/execution


fastqc /cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/inputs/1972885663/S1.fastq.gz -o .
)  > "$out8ae6b526" 2> "$err8ae6b526"
echo $? > /cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/execution
sync


)
mv /cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/execution/rc.tmp /cromwell-executions/rnaseq/8ae6b526-3e45-4b3e-8e6d-298a901b8849/call-fastqc/execution/rc
