#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-getrawdata/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-getrawdata/tmp.0d6b8e4d" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-getrawdata/tmp.0d6b8e4d")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-getrawdata/execution

)
oute347b323="${tmpDir}/out.$$" erre347b323="${tmpDir}/err.$$"
mkfifo "$oute347b323" "$erre347b323"
trap 'rm "$oute347b323" "$erre347b323"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-getrawdata/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-getrawdata/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-getrawdata/execution/stdout' < "$oute347b323" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-getrawdata/execution/stderr' < "$erre347b323" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-getrawdata/execution


ls /home/user08/rna-seq/rawdata/*fastq.gz > rawdatapath.txt
)  > "$oute347b323" 2> "$erre347b323"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-getrawdata/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-getrawdata/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-getrawdata/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-getrawdata/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/e347b323-d0ae-420d-9c5b-e87948761c7b/call-getrawdata/execution/rc
