#!/bin/bash

cd /cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/tmp.1ded33f0" && echo "/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/tmp.1ded33f0")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/execution

)
outf1d89814="${tmpDir}/out.$$" errf1d89814="${tmpDir}/err.$$"
mkfifo "$outf1d89814" "$errf1d89814"
trap 'rm "$outf1d89814" "$errf1d89814"' EXIT
touch '/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/execution/stdout' '/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/execution/stderr'
tee '/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/execution/stdout' < "$outf1d89814" &
tee '/cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/execution/stderr' < "$errf1d89814" >&2 &
(
cd /cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/execution


java -jar trimmomatic-0.39.jar SE -phred33 \
 /cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/inputs/1972885663/S1.fastq.gz output1.fq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
)  > "$outf1d89814" 2> "$errf1d89814"
echo $? > /cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/execution
sync


)
mv /cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/execution/rc.tmp /cromwell-executions/rnaseq/f1d89814-f138-4035-9865-e464b72090fb/call-trim/shard-0/execution/rc
