#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-getrawdata/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-getrawdata/tmp.b3dde01d" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-getrawdata/tmp.b3dde01d")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-getrawdata/execution

)
outa7f1659e="${tmpDir}/out.$$" erra7f1659e="${tmpDir}/err.$$"
mkfifo "$outa7f1659e" "$erra7f1659e"
trap 'rm "$outa7f1659e" "$erra7f1659e"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-getrawdata/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-getrawdata/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-getrawdata/execution/stdout' < "$outa7f1659e" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-getrawdata/execution/stderr' < "$erra7f1659e" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-getrawdata/execution


ls /home/user08/rna-seq/rawdata/*fastq.gz > rawdatapath.txt
)  > "$outa7f1659e" 2> "$erra7f1659e"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-getrawdata/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-getrawdata/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-getrawdata/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-getrawdata/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/a7f1659e-4fa2-4cda-904f-2478c48b0af7/call-getrawdata/execution/rc
