#!/bin/bash

cd /cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/tmp.cd1f04a2" && echo "/cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/tmp.cd1f04a2")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/execution

)
out3ca32dab="${tmpDir}/out.$$" err3ca32dab="${tmpDir}/err.$$"
mkfifo "$out3ca32dab" "$err3ca32dab"
trap 'rm "$out3ca32dab" "$err3ca32dab"' EXIT
touch '/cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/execution/stdout' '/cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/execution/stderr'
tee '/cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/execution/stdout' < "$out3ca32dab" &
tee '/cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/execution/stderr' < "$err3ca32dab" >&2 &
(
cd /cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/execution


fastqc /cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/inputs/1972885663/S1.R2.fastq.gz -o .
)  > "$out3ca32dab" 2> "$err3ca32dab"
echo $? > /cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/execution
sync


)
mv /cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/execution/rc.tmp /cromwell-executions/rnaseq/3ca32dab-fba9-45f3-8cec-195797c83355/call-fastqc/shard-1/execution/rc
