#!/bin/bash

cd /cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/tmp.18609f2c" && echo "/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/tmp.18609f2c")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/execution

)
out7847a515="${tmpDir}/out.$$" err7847a515="${tmpDir}/err.$$"
mkfifo "$out7847a515" "$err7847a515"
trap 'rm "$out7847a515" "$err7847a515"' EXIT
touch '/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/execution/stdout' '/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/execution/stderr'
tee '/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/execution/stdout' < "$out7847a515" &
tee '/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/execution/stderr' < "$err7847a515" >&2 &
(
cd /cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/execution


fastqc /cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/inputs/1972885663/S1.R2.fastq.gz -o .
)  > "$out7847a515" 2> "$err7847a515"
echo $? > /cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/execution
sync


)
mv /cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/execution/rc.tmp /cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-fastqc/shard-1/execution/rc
