#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-getrawdata/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-getrawdata/tmp.71fe7c6d" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-getrawdata/tmp.71fe7c6d")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-getrawdata/execution

)
out7847a515="${tmpDir}/out.$$" err7847a515="${tmpDir}/err.$$"
mkfifo "$out7847a515" "$err7847a515"
trap 'rm "$out7847a515" "$err7847a515"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-getrawdata/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-getrawdata/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-getrawdata/execution/stdout' < "$out7847a515" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-getrawdata/execution/stderr' < "$err7847a515" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-getrawdata/execution


ls /home/user08/rna-seq/rawdata/*fastq.gz > rawdatapath.txt
)  > "$out7847a515" 2> "$err7847a515"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-getrawdata/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-getrawdata/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-getrawdata/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-getrawdata/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/7847a515-4fc6-4a98-9e52-4c8e38895d14/call-getrawdata/execution/rc
