#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-getrawdata/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-getrawdata/tmp.a316826e" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-getrawdata/tmp.a316826e")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-getrawdata/execution

)
out37a39970="${tmpDir}/out.$$" err37a39970="${tmpDir}/err.$$"
mkfifo "$out37a39970" "$err37a39970"
trap 'rm "$out37a39970" "$err37a39970"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-getrawdata/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-getrawdata/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-getrawdata/execution/stdout' < "$out37a39970" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-getrawdata/execution/stderr' < "$err37a39970" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-getrawdata/execution


ls /home/user08/rna-seq/rawdata/*fastq.gz > rawdatapath.txt
)  > "$out37a39970" 2> "$err37a39970"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-getrawdata/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-getrawdata/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-getrawdata/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-getrawdata/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-getrawdata/execution/rc
