#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getrawdata/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getrawdata/tmp.d9b0e117" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getrawdata/tmp.d9b0e117")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getrawdata/execution

)
outcfd0ebae="${tmpDir}/out.$$" errcfd0ebae="${tmpDir}/err.$$"
mkfifo "$outcfd0ebae" "$errcfd0ebae"
trap 'rm "$outcfd0ebae" "$errcfd0ebae"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getrawdata/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getrawdata/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getrawdata/execution/stdout' < "$outcfd0ebae" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getrawdata/execution/stderr' < "$errcfd0ebae" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getrawdata/execution


ls /home/user08/rna-seq/rawdata/*fastq.gz > rawdatapath.txt
)  > "$outcfd0ebae" 2> "$errcfd0ebae"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getrawdata/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getrawdata/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getrawdata/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getrawdata/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/cfd0ebae-b876-4cc3-a7ec-7951dd3b8810/call-getrawdata/execution/rc
