#!/bin/bash

cd /cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/tmp.3844c4c3" && echo "/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/tmp.3844c4c3")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/execution

)
out40887bb3="${tmpDir}/out.$$" err40887bb3="${tmpDir}/err.$$"
mkfifo "$out40887bb3" "$err40887bb3"
trap 'rm "$out40887bb3" "$err40887bb3"' EXIT
touch '/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/execution/stdout' '/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/execution/stderr'
tee '/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/execution/stdout' < "$out40887bb3" &
tee '/cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/execution/stderr' < "$err40887bb3" >&2 &
(
cd /cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/execution


fastqc /cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/inputs/1972885663/S1.R1.fastq.gz /cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/inputs/1972885663/S1.R2.fastq.gz -o .
)  > "$out40887bb3" 2> "$err40887bb3"
echo $? > /cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/execution
sync


)
mv /cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/execution/rc.tmp /cromwell-executions/rnaseq/40887bb3-909a-4b4e-b3e3-c2aa3caa3bea/call-fastqc/execution/rc
