#!/bin/bash

cd /cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/tmp.90c9796a" && echo "/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/tmp.90c9796a")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/execution

)
out37a39970="${tmpDir}/out.$$" err37a39970="${tmpDir}/err.$$"
mkfifo "$out37a39970" "$err37a39970"
trap 'rm "$out37a39970" "$err37a39970"' EXIT
touch '/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/execution/stdout' '/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/execution/stderr'
tee '/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/execution/stdout' < "$out37a39970" &
tee '/cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/execution/stderr' < "$err37a39970" >&2 &
(
cd /cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/execution


fastqc /cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/inputs/1972885663/S1.R2.fastq.gz -o .
)  > "$out37a39970" 2> "$err37a39970"
echo $? > /cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/execution
sync


)
mv /cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/execution/rc.tmp /cromwell-executions/rnaseq/37a39970-2284-4262-8eb2-466fd81dec84/call-fastqc/shard-1/execution/rc
