#!/bin/bash

cd /cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/tmp.1aef8c75" && echo "/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/tmp.1aef8c75")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/execution

)
out444fbcb8="${tmpDir}/out.$$" err444fbcb8="${tmpDir}/err.$$"
mkfifo "$out444fbcb8" "$err444fbcb8"
trap 'rm "$out444fbcb8" "$err444fbcb8"' EXIT
touch '/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/execution/stdout' '/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/execution/stderr'
tee '/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/execution/stdout' < "$out444fbcb8" &
tee '/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/execution/stderr' < "$err444fbcb8" >&2 &
(
cd /cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/execution


fastqc /cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/inputs/1972885663/S1.R1.fastq.gz /cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/inputs/1972885663/S1.R2.fastq.gz -o .
)  > "$out444fbcb8" 2> "$err444fbcb8"
echo $? > /cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/execution
sync


)
mv /cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/execution/rc.tmp /cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-fastqc/execution/rc
