#!/bin/bash

cd /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/tmp.613bd8c4" && echo "/cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/tmp.613bd8c4")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/execution

)
outa64a0288="${tmpDir}/out.$$" erra64a0288="${tmpDir}/err.$$"
mkfifo "$outa64a0288" "$erra64a0288"
trap 'rm "$outa64a0288" "$erra64a0288"' EXIT
touch '/cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/execution/stdout' '/cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/execution/stderr'
tee '/cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/execution/stdout' < "$outa64a0288" &
tee '/cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/execution/stderr' < "$erra64a0288" >&2 &
(
cd /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/execution


fastqc /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/inputs/1972885663/S1.fastq.gz /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/inputs/1972885663/S2.fastq.gz -o .
)  > "$outa64a0288" 2> "$erra64a0288"
echo $? > /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/execution
sync


)
mv /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/execution/rc.tmp /cromwell-executions/rnaseq/a64a0288-ca8f-4548-8b37-7d13f7694063/call-fastqc/execution/rc
