#!/bin/bash

cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-getrawdata/execution
tmpDir=$(mkdir -p "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-getrawdata/tmp.020daf4d" && echo "/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-getrawdata/tmp.020daf4d")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-getrawdata/execution

)
out444fbcb8="${tmpDir}/out.$$" err444fbcb8="${tmpDir}/err.$$"
mkfifo "$out444fbcb8" "$err444fbcb8"
trap 'rm "$out444fbcb8" "$err444fbcb8"' EXIT
touch '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-getrawdata/execution/stdout' '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-getrawdata/execution/stderr'
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-getrawdata/execution/stdout' < "$out444fbcb8" &
tee '/home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-getrawdata/execution/stderr' < "$err444fbcb8" >&2 &
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-getrawdata/execution


ls /home/user08/rna-seq/rawdata/*fastq.gz > rawdatapath.txt
)  > "$out444fbcb8" 2> "$err444fbcb8"
echo $? > /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-getrawdata/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-getrawdata/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-getrawdata/execution
sync


)
mv /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-getrawdata/execution/rc.tmp /home/user08/rna-seq/rnaseq_wdl/cromwell-executions/rnaseq/444fbcb8-f7f5-4a33-8c94-74ec5711ac34/call-getrawdata/execution/rc
