#!/bin/bash

cd /cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/execution
tmpDir=$(mkdir -p "/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/tmp.ee31eda6" && echo "/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/tmp.ee31eda6")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/execution

)
outc3e14391="${tmpDir}/out.$$" errc3e14391="${tmpDir}/err.$$"
mkfifo "$outc3e14391" "$errc3e14391"
trap 'rm "$outc3e14391" "$errc3e14391"' EXIT
touch '/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/execution/stdout' '/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/execution/stderr'
tee '/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/execution/stdout' < "$outc3e14391" &
tee '/cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/execution/stderr' < "$errc3e14391" >&2 &
(
cd /cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/execution


fastqc /cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/inputs/1972885663/S1.R1.fastq.gz -o .
)  > "$outc3e14391" 2> "$errc3e14391"
echo $? > /cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/execution
sync


)
mv /cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/execution/rc.tmp /cromwell-executions/rnaseq/c3e14391-8dd9-4bba-bd37-76962d4bd021/call-fastqc/shard-0/execution/rc
